DATASMITH_CATEGORY = "Datasmith"

DATASMITH_EXPORTOPTIONS_INCLUDESELECTEDONLY_TOOLTIP = "Export Selected Objects Only"
DATASMITH_EXPORTOPTIONS_INCLUDEALLVISIBLEOBJECTS_TOOLTIP = "Export All Visible Objects"
DATASMITH_EXPORTOPTIONS_ANIMATEDTRANSFORMSACTIVESEGMENT_TOOLTIP = "Export Animation(Active Time Segment)"
DATASMITH_EXPORTOPTIONS_ANIMATEDTRANSFORMSCURRENTFRAMEONLY_TOOLTIP = "Don't Export Animation(Use Current Frame)"
DATASMITH_ADD_ATTRIBUTES_MODIFIER_TEXT =  "Add Attributes Modifier"
DATASMITH_ADD_ATTRIBUTES_MODIFIER_TOOLTIP =  "Add Datasmith Attributes Modifier"
DATASMITH_EXPORTOPTIONS_XREFSCENES_TOOLTIP = "Enables export/sync of XRef Scenes"