version: '3'
services:
  loadbalancer:
    build:
      context: .
      dockerfile: nginx_dockerfile
    ports:
    - "80:80" 
    networks:
    - network_jupiter

    depends_on: 
      - unreal_cloud_ddc
  scylla:
    logging:
      driver: none
    image: scylladb/scylla
    command: --smp=1 --developer-mode 1
    volumes:
    - scylla-volume-1:/var/lib/scylla
    networks:
    - network_jupiter
    ports:
    - "9042:9042"
  unreal_cloud_ddc:
    build:
      context: "../../../"
      dockerfile: Programs/UnrealCloudDDC/dockerfile
    ports:
    - "8080:8080" 
    networks:
    - network_jupiter
    environment:
    - Jupiter__CurrentSite=docker-compose
    - Serilog__MinimumLevel__Default=Debug
    - CORECLR_ENABLE_PROFILING=0
    - Auth__Enabled=false
    - Replication__CurrentSite=docker-compose
    - Scylla__ContactPoints__0=scylla
    - Scylla__LocalDatacenterName=datacenter1
    - Scylla__LocalKeyspaceSuffix=dc1
    links:
    - scylla
    labels:
      com.datadoghq.ad.logs: '[{"source":"csharp", "service": "jupiter"}]'
volumes:
  scylla-volume-1:
networks:
  network_jupiter:
    driver: bridge
